@startuml
left to right direction

:Usuario: as U
:Broker MQTT: as M <<Servicio>>

(Observar localmente el estado de luz) as OLL
(Observar localmente la posición de actuador) as OPL
(Modificar localmente el estado de luz) as MLL
(Modificar localmente la posición de actuador) as MPL
(Observar estado de luz remota) as OLR
(Modificar estado de luz remota) as MLR
(Observar posición de actuador remoto) as OPR
(Modificar posición de actuador remoto) as MPR

U --> OLL
U --> OPL
U --> MLL
U --> MPL
U --> OLR
U --> MLR
U --> OPR
U --> MPR

OLR --> M
MLR --> M
OPR --> M
MPR --> M

@enduml
